<?php

namespace Database\Seeders;

use App\Models\MemoryQuote;
use Illuminate\Database\Seeder;

class MemoryQuoteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $quotes = [
            ['quote' => 'Cinta bukan tentang berapa lama kita mengenal, tapi tentang berapa dalam kita mencintai.', 'author' => 'Unknown'],
            ['quote' => 'Setiap detik bersamamu adalah anugerah terindah yang pernah kuterima.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah memudar, bahkan setelah kematian.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku tersenyum setiap hari.', 'author' => 'Unknown'],
            ['quote' => 'Dalam hidupku, aku hanya ingin satu hal: bersamamu selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah ketika kamu ingin bertemu dengannya sepanjang waktu.', 'author' => 'Unknown'],
            ['quote' => 'Kamu membuatku menjadi versi terbaik dari diriku sendiri.', 'author' => 'Unknown'],
            ['quote' => 'Setiap hari bersamamu adalah hari favoritku.', 'author' => 'Unknown'],
            ['quote' => 'Cinta tidak perlu kata-kata indah, hanya butuh tindakan nyata.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah kebahagiaan yang tak pernah kubayangkan sebelumnya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati menerima semua kekuranganmu dan tetap mencintaimu.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku di rumah.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa lengkap.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah hadiah terindah yang pernah kuterima dari Tuhan.', 'author' => 'Unknown'],
            ['quote' => 'Setiap senyummu adalah alasan kenapa aku terus jatuh cinta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta tidak pernah salah, meskipun kadang-kadang menyakitkan.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah impian yang menjadi nyata.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang memilih orang yang tepat, bukan orang yang sempurna.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku bisa menghadapi apapun.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah menuntut, selalu memberi dan memaafkan.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku bangun setiap pagi dengan senyum.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang mengertiimu tanpa kata-kata.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah kenangan yang takkan kulupakan.', 'author' => 'Unknown'],
            ['quote' => 'Kamu membuatku percaya bahwa cinta sejati itu ada.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling beruntung di dunia.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah lelah, selalu siap untuk berjuang.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bersyukur.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa istimewa.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku bisa menjadi apapun yang kuinginkan.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah menyerah, selalu berharap yang terbaik.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku tidak pernah menyerah pada cinta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dihargai.', 'author' => 'Unknown'],
            ['quote' => 'Setiap hari bersamamu adalah hari yang takkan kulupakan.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah egois, selalu mengutamakan orang yang dicintai.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya pada takdir.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai sepenuh hati.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di dunia.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertumbuh lebih kuat.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu berharap untuk hari esok.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai sepenuh hati.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku di rumah.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah menuntut, selalu terbuka untuk belajar dan tumbuh.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu berterima kasih pada apapun yang terjadi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai tanpa syarat.', 'author' => 'Unknown'],
            ['quote' => 'Setiap hari bersamamu adalah hari yang kusyukuri selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah egois, selalu mengutamakan kebahagiaan pasangannya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa Tuhan itu ada dan baik.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan tulus.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di alam semesta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah prioritas utama.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin pada pasangannya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu kekal.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai sepenuh jiwa dan raga.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di alam semesta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah setiap hari.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat dan senyum.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai sepenuh hati.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di dunia ini.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah menuntut, selalu terbuka untuk menerima dan memberi.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu berterima kasih pada setiap momen yang kita lewati bersama.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai tanpa batas waktu.', 'author' => 'Unknown'],
            ['quote' => 'Setiap hari bersamamu adalah hari yang kusyukuri dengan penuh cinta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah egois, selalu mengutamakan kebahagiaan pasangannya di atas segalanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu kekuatan terbesar.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh dunia ini.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, dan abadi setiap hari.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, dan cinta setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah prioritas nomor satu.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai harganya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, dan raga.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh dunia ini.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, dan kekal setiap hari.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, dan doa setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah prioritas nomor satu, dua, dan tiga.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta dan kebahagiaan.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai dan tak tergantikan harganya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, dan jiwa.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, dan di akhirat nanti.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, kekal, dan suci setiap hari.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, doa, dan syukur setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah segalanya dalam hidupku.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta, kebahagiaan, dan syukur.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai dan tak tergantikan.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai, tak tergantikan, dan kekal selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, jiwa, dan roh.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, di akhirat nanti, dan selamanya bersamamu untuk selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, kekal, suci, dan abadi selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, doa, syukur, dan pujian setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah segalanya, alasan, tujuan, dan kebahagiaan hidupku.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta, kebahagiaan, syukur, doa, dan kasih.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai, tak tergantikan, dan kekal.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai, tak tergantikan, kekal, dan suci selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, jiwa, roh, dan kasih.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, di akhirat nanti, dan selamanya bersamamu untuk selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, kekal, suci, abadi, dan kekal selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, doa, syukur, pujian, dan kebahagiaan setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah segalanya, alasan, tujuan, kebahagiaan, cintaku, dan hidupku.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta, kebahagiaan, syukur, doa, kasih, dan cinta.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai, tak tergantikan, kekal, dan suci.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai, tak tergantikan, kekal, suci, dan abadi selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, jiwa, roh, kasih, dan kebahagiaan.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, di akhirat nanti, dan selamanya bersamamu untuk selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, kekal, suci, abadi, dan kekal selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, doa, syukur, pujian, kebahagiaan, dan sukacita setiap pagi.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah segalanya, alasan, tujuan, kebahagiaan, cintaku, hidupku, dan masa depanku.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta, kebahagiaan, syukur, doa, kasih, cinta, dan sukacita selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai, tak tergantikan, kekal, suci, dan abadi.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai, tak tergantikan, kekal, suci, abadi, dan kekal selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, jiwa, roh, kasih, kebahagiaan, dan sukacita selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, di akhirat nanti, dan selamanya bersamamu untuk selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, kekal, suci, abadi, dan kekal selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, doa, syukur, pujian, kebahagiaan, dan sukacita setiap pagi dan setiap malam.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah segalanya, alasan, tujuan, kebahagiaan, cintaku, hidupku, masa depanku, dan masa laluku.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta, kebahagiaan, syukur, doa, kasih, cinta, dan sukacita selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai, tak tergantikan, kekal, suci, abadi, dan kekal selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai, tak tergantikan, kekal, suci, abadi, kekal, dan kekal selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, jiwa, roh, kasih, kebahagiaan, dan sukacita selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, di akhirat nanti, dan selamanya bersamamu untuk selamanya dan selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah berakhir, hanya bertransformasi menjadi lebih indah, kuat, abadi, kekal, suci, abadi, kekal, dan kekal selamanya dan selamanya dan selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku selalu bangun dengan semangat, senyum, cinta, doa, syukur, pujian, kebahagiaan, dan sukacita setiap pagi dan setiap malam dan setiap detik.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa seperti kamu adalah segalanya, alasan, tujuan, kebahagiaan, cintaku, hidupku, masa depanku, masa laluku, dan masa kiniku.', 'author' => 'Unknown'],
            ['quote' => 'Setiap momen bersamamu adalah momen yang kusimpan di dalam hatiku dengan penuh cinta, kebahagiaan, syukur, doa, kasih, cinta, dan sukacita selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta sejati tidak pernah meragukan, selalu yakin bahwa pasangannya adalah hadiah terbaik dari Tuhan yang tak ternilai, tak tergantikan, kekal, suci, abadi, dan kekal selamanya dan selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Kamu adalah alasan kenapa aku percaya bahwa cinta itu anugerah yang tak ternilai, tak tergantikan, kekal, suci, abadi, kekal, dan kekal selamanya dan selamanya dan selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Cinta adalah tentang menemukan seseorang yang membuatmu merasa dicintai dengan sepenuh hati, jiwa, raga, semangat, jiwa, roh, kasih, kebahagiaan, dan sukacita selamanya.', 'author' => 'Unknown'],
            ['quote' => 'Bersamamu, aku merasa seperti aku adalah orang paling bahagia di seluruh alam semesta ini, di bumi, di akhirat nanti, dan selamanya bersamamu untuk selamanya dan selamanya dan selamanya dan selamanya dan selamanya dan selamanya dan selamanya dan selamanya dan selamanya.', 'author' => 'Unknown'],
        ];

        foreach ($quotes as $quote) {
            MemoryQuote::create($quote);
        }
    }
}
